### ISSUE TITLE
missing groups_sync_with_enrolment() function

### ISSUE THREAD

**Issue by js0000** [mihir-thakkar/moodle-enrol_metabulk#2]
hi

i have installed the plugin and get this error:

> Fatal error: Call to undefined function groups_sync_with_enrolment() in /moodle/enrol/metabulk/locallib.php on line 384

i searched the entire moodle tree and found nothing matching this name.

this is the version i have installed. i am running moodle 2.8.8+

> $plugin->version   = 2015082100;        // The current plugin version (Date: YYYYMMDDXX)

**Comment by mihir-thakkar** [comment]
Hi, Thanks for reporting!
That function is defined in group/lib.php Line 1037
Here it is: https://github.com/moodle/moodle/blob/MOODLE_29_STABLE/group/lib.php/#L1037
I am not sure how you got that error. I'll let you know when I find a way to fix that for you.

**Comment by js0000** [comment]
but i am running 2.8!

and it says ok for 2.8 on https://moodle.org/plugins/pluginversions.php?plugin=enrol_metabulk

then i looked to pull another branch or tag and there are none in the repository!

**Comment by mihir-thakkar** [comment]
You're right! Group sync feature will not work in 2.8.
Sorry for inconvenience.
And thanks for reporting the issue, I'll update the plugin's directory. :)

**Comment by mihir-thakkar** [comment]
groups_sync_with_enrolment() function is not present in version 2.8 so groups sync is not functional.
I have removed 2.8 as supported versions in the plugins directory.
Closing this issue! :)

**Comment by js0000** [comment]
thx for following up.
