### ISSUE TITLE
undefined function error

### ISSUE THREAD

**Issue by rimacher** [mihir-thakkar/moodle-enrol_metabulk#3]
Hello,

I get a 'Fatal error: Call to undefined function groups_sync_with_enrolment() in /data/moodlegit/moodle/enrol/metabulk/locallib.php on line 384' after creating or updating the Bulk meta course link, the link is created regardless.

I also get the same error when linking courses. In this case, also, the courses are added.

**Comment by mihir-thakkar** [comment]
Hi, I think you are using an earlier version. This plugin is for Moodle 2.9.
What version are you using?

**Comment by rimacher** [comment]
Yes, I'm using 2.8. Will it be possible to release a 2.8 version?

**Comment by mihir-thakkar** [comment]
For implementing the groups synchronisation, I have used an existing function "groups_sync_with_enrolment()". And this function is not defined in pre 2.9 versions of moodle enrolment APIs.
So you see, without this function in the enrolment API, I won't be able to implement this for 2.8.
I am sorry for the inconvenience caused to you. But you can upgrade your version to 2.9, it is pretty cool.
